apiVersion: v1
kind: PersistentVolume
metadata:
  name: neo4j-data-pv
  labels:
    app: neo4j-data
    type: local
spec:
  capacity:
    storage: 6Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: "/pv/explorer/neo4j-data"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - cal4-worker-dk
  claimRef:
    name: neo4j-data-pvc
    namespace: dk-tax
