apiVersion: v1
kind: PersistentVolume
metadata:
  name: explorer-logs-pv
  labels:
    app: explorer-logs
    type: local
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: "/pv/explorer/explorer-logs"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - cal4-worker-dk
  claimRef:
    name: explorer-logs-pvc
    namespace: dk-tax