apiVersion: v1
kind: Service
metadata:
  name: neo4j-service
  namespace: dk-tax
spec:
  ports:
  - name: ui
    nodePort: 30388
    port: 7473
    protocol: TCP
    targetPort: 7473
  - name: api
    nodePort: 31019
    port: 7474
    protocol: TCP
    targetPort: 7474
  - name: bolt
    nodePort: 32129
    port: 7687
    protocol: TCP
    targetPort: 7687
  selector:
    app: neo4j
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo4j-deployment
  namespace: dk-tax
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neo4j
  template:
    metadata:
      labels:
        app: neo4j
    spec:
      containers:
        - name: neo4j
          image: dk-harbor.eastus.cloudapp.azure.com/dk-tax/neo4j:v1
          ports:
            - containerPort: 7474
            - containerPort: 7687
          volumeMounts:
            - name: neo4j-data
              mountPath: /data
            - name: neo4j-logs
              mountPath: /logs
            - name: neo4j-import
              mountPath: /var/lib/neo4j/import/
      volumes:
        - name: neo4j-data
          persistentVolumeClaim:
            claimName: neo4j-data-pvc
        - name: neo4j-logs
          persistentVolumeClaim:
            claimName: neo4j-logs-pvc
        - name: neo4j-import
          hostPath:
            path: /apps/kube-pv/import
            type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4j-data-pvc
  namespace: dk-tax
  labels:
    app: neo4j-data
spec:
  accessModes:
  - ReadWriteOnce   # ReadWriteOnce, ReadOnlyMany or ReadWriteMany
  storageClassName: local-storage
  resources:
    requests:
      storage: 6Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4j-logs-pvc
  namespace: dk-tax
  labels:
    app: neo4j-logs
spec:
  accessModes:
  - ReadWriteOnce   # ReadWriteOnce, ReadOnlyMany or ReadWriteMany
  storageClassName: local-storage
  resources:
    requests:
      storage: 5Gi