apiVersion: v1
kind: Service
metadata:
  name: explorer-app-svc
  namespace: dk-tax
spec:
  selector:
    app: explorer
  ports:
    - name: explorer-port
      protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 32477
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: explorer-app-deploy
  namespace: dk-tax
spec:
  replicas: 1
  selector:
    matchLabels:
      app: explorer
  template:
    metadata:
      labels:
        app: explorer
    spec:
      containers:
        - name: explorer
          image: dk-harbor.eastus.cloudapp.azure.com/dk-tax/explorer-app:v1
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: explorer-data
              mountPath: /opt/murcs/standalone/data
            - name: explorer-logs
              mountPath: /var/log/murcs
            - name: neo4j-import
              mountPath: /neo4j
          env:
            - name: DS_MURCS_DRIVER
              value: mysql
            - name: DS_MURCS_URL
              value: jdbc:mysql://dktax-cal4.eastus.cloudapp.azure.com:30255/murcs?useLegacyDatetimeCode=false&serverTimezone=UTC
            - name: DS_MURCS_USER
              value: murcs
            - name: DS_MURCS_PASSWORD
              value: murcs
            - name: DS_KEYCLOAK_DRIVER
              value: mysql
            - name: KEYCLOAK_HOST
              value: dktax-cal4.eastus.cloudapp.azure.com
            - name: KEYCLOAK_PORT
              value: "31323"
            - name: DS_KEYCLOAK_URL
              value: jdbc:mysql://dktax-cal4.eastus.cloudapp.azure.com:30255/keycloak
            - name: DS_KEYCLOAK_USER
              value: keycloak
            - name: DS_KEYCLOAK_PASSWORD
              value: keycloak
            - name: MURCS_HTTP_PORT
              value: "8081"
            - name: LOGLEVEL
              value: INFO
            - name: EXPLORER_HIBERNATE_SEARCH
              value: "true"

      volumes:
        - name: explorer-data
          persistentVolumeClaim:
            claimName: explorer-data-pvc
        - name: explorer-logs
          persistentVolumeClaim:
            claimName: explorer-logs-pvc
        - name: neo4j-import
          hostPath:
            path: /apps/kube-pv/import
            type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: explorer-data-pvc
  namespace: dk-tax
  labels:
    app: explorer-data
spec:
  accessModes:
  - ReadWriteOnce   # ReadWriteOnce, ReadOnlyMany or ReadWriteMany
  storageClassName: local-storage
  resources:
    requests:
      storage: 7Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: explorer-logs-pvc
  namespace: dk-tax
  labels:
    app: explorer-logs
spec:
  accessModes:
  - ReadWriteOnce   # ReadWriteOnce, ReadOnlyMany or ReadWriteMany
  storageClassName: local-storage
  resources:
    requests:
      storage: 4Gi

