apiVersion: v1
kind: PersistentVolume
metadata:
  name: explorer-db-pv
  labels:
    app: explorer-db
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: "/pv/explorer/explorer-db"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - cal4-worker-dk
  claimRef:
    namespace: dk-tx
    name: explorer-db-pvc
