apiVersion: v1
kind: Service
metadata:
  name: explorer-db-service
  namespace: dk-tax
spec:
  selector:
    app: explorer-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30255
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: explorer-db-deploy
  namespace: dk-tax
spec:
  replicas: 1
  selector:
    matchLabels:
      app: explorer-db
  template:
    metadata:
      labels:
        app: explorer-db
    spec:
      containers:
        - name: explorer-db
          image: dk-harbor.eastus.cloudapp.azure.com/dk-tax/explorer-db:v1
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: murcs
            - name: MYSQL_DATABASE
              value: murcs
      volumes:
        - name: explorer-db
          persistentVolumeClaim:
            claimName: explorer-db-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: explorer-db-pvc
  namespace: dk-tax
  labels:
    app: explorer-db
spec:
  accessModes:
  - ReadWriteOnce   # ReadWriteOnce, ReadOnlyMany or ReadWriteMany
  storageClassName: local-storage
  resources:
    requests:
      storage: 10Gi