apiVersion: v1
kind: Service
metadata:
  name: studiocore-frontend-svc
  namespace: dk-tax
spec:
  type: NodePort
  selector:
    app: studiocore-forntend
    tier: frontend
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 8080
      targetPort: 8080
      nodePort: 32133
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: studiocore-forntend
  namespace: dk-tax
spec:
  selector:
    matchLabels:
      app: studiocore-forntend
      tier: frontend
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: studiocore-forntend
        tier: frontend
    spec:
      containers:
      - name: studiocore-forntend
        image: dk-harbor.eastus.cloudapp.azure.com/dk-tax/studio-core-ui-dktax:v1
        ports:
        - containerPort: 8080
