apiVersion: v1
kind: Service
metadata:
  name: studiocore-backend-svc
  namespace: dk-tax
spec:
  type: NodePort
  selector:
    app: studiocore-backend
    tier: backend
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 8080
      targetPort: 8080
      nodePort: 32233
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: studiocore-backend-config
  namespace: dk-tax
data:
  DB_HOST: "dktax-cal4.eastus.cloudapp.azure.com"
  DB_PORT: "30874"
  DB_NAME: "Studio_Core"
  DB_USERNAME: "sa"
  MURCS_SERVER_IP: "dktax-cal4.eastus.cloudapp.azure.com"
  MURCS_SERVER_PORT: "32477"
  STUDIO_UI_LINK: "http://dktax-cal4.eastus.cloudapp.azure.com:32389/studiocore/"
  SERVER_PORT: "32133"
  KEYCLOAK_AUTH_SERVER_URL: "http://dktax-cal4.eastus.cloudapp.azure.com:31323/auth"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: studiocore-backend
  namespace: dk-tax
spec:
  replicas: 1
  selector:
    matchLabels:
      app: studiocore-backend
      tier: backend
  template:
    metadata:
      labels:
        app: studiocore-backend
        tier: backend
    spec:
      containers:
      - name: studiocore-backend
        image: dk-harbor.eastus.cloudapp.azure.com/dk-tax/studio-core-ws-dktax:v3
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: studiocore-backend-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: studiocore-backend-config
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: studiocore-backend-config
              key: DB_NAME
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: studiocore-backend-config
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql
              key: MSSQL_SA_PASSWORD
        - name: MURCS_SERVER_IP
          valueFrom:
            configMapKeyRef:
              name: studiocore-backend-config
              key: MURCS_SERVER_IP
        - name: MURCS_SERVER_PORT
          valueFrom:
            configMapKeyRef:
              name: studiocore-backend-config
              key: MURCS_SERVER_PORT
        - name: STUDIO_UI_LINK
          valueFrom:
            configMapKeyRef:
              name: studiocore-backend-config
              key: STUDIO_UI_LINK
        - name: SERVER_PORT
          valueFrom:
            configMapKeyRef:
              name: studiocore-backend-config
              key: SERVER_PORT
        - name: KEYCLOAK_AUTH_SERVER_URL
          valueFrom:
            configMapKeyRef:
              name: studiocore-backend-config
              key: KEYCLOAK_AUTH_SERVER_URL
