apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mssql-sdp # name of the StatefulSet workload, the SQL Server instance name is derived from this. We suggest to keep this name same as the .spec.template.metadata.labels, .spec.selector.matchLabels and .spec.serviceName to avoid confusion.
  namespace: dk-tax
spec:
  serviceName: "mssql" # serviceName is the name of the service that governs this StatefulSet. This service must exist before the StatefulSet, and is responsible for the network identity of the set.
  replicas: 1 # only one pod, with one SQL Server instance deployed.
  selector:
    matchLabels:
      app: mssql-sdp
      tier: database  # this has to be the same as .spec.template.metadata.labels
  template:
    metadata:
      labels:
        app: mssql-sdp
        tier: database # this has to be the same as .spec.selector.matchLabels, as documented here:
    spec:
      securityContext:
        fsGroup: 10001
      containers:
      - name: mssql-sdp # container name within the pod.
        image: dk-harbor.eastus.cloudapp.azure.com/dk-tax/mcr.microsoft.com/mssql/server:2019
        ports:
        - containerPort: 1433
          name: tcpsql
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_ENABLE_HADR
          value: "1"
        - name: MSSQL_AGENT_ENABLED
          value: "1"
        - name: MSSQL_SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql
              key: MSSQL_SA_PASSWORD
        volumeMounts:
        - name: mssql-sdp
          mountPath: "/var/opt/mssql"
  volumeClaimTemplates:
  - metadata:
      name: mssql-sdp
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: local-storage
      resources:
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mssql-sdp-service
  namespace: dk-tax
spec:
  type: NodePort
  selector:
    app: mssql-sdp
    tier: database
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 1433
      targetPort: 1433
      nodePort: 31748
