apiVersion: apps/v1
kind: Deployment
metadata:
  name: sdp-api
  namespace: dk-tax
spec:
  selector:
    matchLabels:
      app: sdp-api
      tier: backend
  replicas: 1 # tells deployment to run 1 pod matching the template
  template:
    metadata:
      labels:
        app: sdp-api
        tier: backend
    spec:
      containers:
      - name: sdp-api
        image: dk-harbor.eastus.cloudapp.azure.com/dk-tax/cal4-sdp-api:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sdp-api-service
  namespace: dk-tax
spec:
  type: NodePort
  selector:
    app: sdp-api
    tier: backend
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 80
      targetPort: 80
      nodePort: 31491
