apiVersion: batch/v1
kind: Job
metadata:
  name: sdp-db-5-insertscripts-job
  namespace: dk-tax
spec:
  template:
    spec:
      containers:
      - name: sdp-db-insertscripts
        image: dk-harbor.eastus.cloudapp.azure.com/dk-tax/custom-mssql-tools18:v1
        command: 
        - /bin/bash
        - -c
        - |
          echo "Waiting for SQL Server to start..."
          until /opt/mssql-tools/bin/sqlcmd -S dktax-cal4.eastus.cloudapp.azure.com,31748 -U sa -P $MSSQL_SA_PASSWORD -Q "SELECT 1;" > /dev/null 2>&1; do
            sleep 1
          done
          echo "SQL Server started."
          echo "Running the script..."
          /opt/mssql-tools/bin/sqlcmd -S dktax-cal4.eastus.cloudapp.azure.com,31748 -U sa -P $MSSQL_SA_PASSWORD -i /scripts/sdp/5_Insert_Lookup_Script.sql
        env:
        - name: MSSQL_SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql
              key: MSSQL_SA_PASSWORD
        volumeMounts:
        - name: scripts-volume
          mountPath: /scripts
      volumes:
      - name: scripts-volume
        hostPath:
          path: /apps/kube-pv/scripts-volume
      restartPolicy: Never
  backoffLimit: 4
