apiVersion: apps/v1
kind: Deployment
metadata:
  name: sdp-ui
  namespace: dk-tax
spec:
  selector:
    matchLabels:
      app: sdp-ui
      tier: frontend
  replicas: 1 # tells deployment to run 1 pod matching the template
  template:
    metadata:
      labels:
        app: sdp-ui
        tier: frontend
    spec:
      containers:
      - name: sdp-ui
        image: dk-harbor.eastus.cloudapp.azure.com/dk-tax/cal4-sdp-ui:v2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sdp-ui-service
  namespace: dk-tax
spec:
  type: NodePort
  selector:
    app: sdp-ui
    tier: frontend
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 80
      targetPort: 80
      nodePort: 31420

