apiVersion: v1
kind: PersistentVolume
metadata:
  name: tep-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /apps/kube-pv/data-tep