apiVersion: v1
kind: ConfigMap
metadata:
  name: ffui-dev-config
  namespace: dev
data:
  ENABLE_KEYCLOAK: "false"
  KEYCLOAKCONFIGURL: "https://dxcmodstudio-itp.elabs.svcs.entsvcs.net/auth"
  KEYCLOAKCONFIGREALM: "dxcstudio"
  KEYCLOAKCONFIGCLIENTID: "dxcstudioui"
  PRODUCTION: "true"
  BASE_URI: "http://172.206.210.42:31696"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ffui-dev-deployment
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ffui-dev
  template:
    metadata:
      labels:
        app: ffui-dev
    spec:
      containers:
      - name: ffui-dev-container
        image: modstudiocrpoc.azurecr.io/studiofactory:v1
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: ffui-dev-config
#        readinessProbe:
#          httpGet:
#            path: /api/health
#            port: 80
#        livenessProbe:
#          httpGet:
#            path: /api/health
#            port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ffui-dev-service
  namespace: dev
spec:
  type: NodePort
  ports:
    - port: 8443
      targetPort: 80
      nodePort: 32632
  selector:
    app: ffui-dev
